apiVersion: v1
kind: Pod
metadata:
  name: my-pod5
spec:
  containers:
  - name: my-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo [$(date):$HOSTNAME] Hello >> /mnt/data/hello.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: /mnt/data
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: retain-pvc